language: node_js
sudo: false
script: gulp travis
node_js:
  - "4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  firefox: "42.0"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
